server:
  port: 8002

spring:
  application:
    name: msvc-cursos
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/msvc_cursos
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

logging:
  level:
    org:
      hibernate:
        sql: debug
